### ISSUE TITLE
No internet connection on GO2 Edu

### ISSUE THREAD

**Issue by Cavalletta98** [IntelligentRoboticsLabs/go2_robot#11]
Hi, i have a GO2 Edu with a jetson mounted on it. I noticed that is has no internet connection. How do you manange to connect to the robot or installing ROS Humble on it?

**Comment by Juancams** [comment]
Hello @Cavalletta98 

To connect it to the internet, I connect the robot to a router through an RJ45.

We have the robot with Ubuntu 20, which is how it comes by default, so we have ros foxy and noetic. In the future we will update the robot's jetpack to be able to use humble or jazzy.

**Comment by Cavalletta98** [comment]
Is there a router mounted on the robot?

**Comment by Juancams** [comment]
No, the robot by default does not come with a router. You would have to connect it to one you have lying around and then give the network to that router, or you can also put a USB adapter on it to connect it to a network.

**Comment by mspringer1** [comment]
In some documentation I read that this model: "TP-Link TL-WN722N High Gain WLAN USB Adapter" works out of the box with the Go2 and is used by others, so no additional drivers need to be installed.

**Comment by Juancams** [comment]
The robot can set up its own wifi, but it appears to be connected to another part of the robot, not to the jetson. When I connect and try to see the topics it doesn't work, I thought that modifying the dds could do the same, but in reality the computer does not have any new network interface through which to send the information.

The only way I can think of for now is to connect a tp link or a router to the robot.

**Comment by Cavalletta98** [comment]
ok thank you so much
