### ISSUE TITLE
Build of the workspace failed

### ISSUE THREAD

**Issue by RiccardoZuppetti** [IntelligentRoboticsLabs/go2_robot#16]
Following the instructions in the README, I've encountered this error when building the workspace:

``` bash
In file included from /root/catkin_ws/src/go2_robot/go2_driver/src/go2_driver/go2_driver.cpp:31:
/root/catkin_ws/src/go2_robot/go2_driver/include/go2_driver/go2_driver.hpp:45:10: fatal error: nlohmann/json.hpp: No such file or directory
   45 | #include "nlohmann/json.hpp"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

How can I solve this?

**Comment by tgodfrey0** [comment]
Hi, I was also experiencing this issue. I managed to get the WS to build by cloning the JSON repo [here](https://github.com/nlohmann/json) and copying the `include/nlohmann` folder into `~/ros2_ws/src/go2_robot/go2_driver/include/`

**Comment by RiccardoZuppetti** [comment]
Hi @tgodfrey0, thanks for the hint, everything builds fine now. Closing for the time being.
