### ISSUE TITLE
About This Repo

### ISSUE THREAD

**Issue by cyhunblr** [IntelligentRoboticsLabs/go2_robot#17]
Hi!
I'am a little be confused. This repository for simulation or not? Because there is no com protocol or something.

**Comment by Juancams** [comment]
Hello!

The only current function of this repository is to make a wrap between the unitree go2 sdk and ros2, in which some topics are provided such as `/cmd_vel`, `/robot_description`, `/joint_states`...

Regarding the simulation, we hope to have it in a couple of weeks.

Regards.

**Comment by cyhunblr** [comment]
@Juancams thanks for your answer. I have a Unitree Go2 Pro and also I didn't get any kind of topic (joints,sensors etc.). Any your suggestion?

**Comment by cyhunblr** [comment]
I got an email from unitree. Go2 Pro doesn't supported.
